name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-ui-tests:
    name: Run Tests
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: Run Enro UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        id: testing
        continue-on-error: true
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            adb logcat -c                             # clear logs
            touch ~/appemulator.log                    # create log file
            chmod 777 ~/appemulator.log                # allow writing to log file
            adb logcat >> ~/appemulator.log &          # pipe all logcat messages into log file as a background process
            ./gradlew :enro:connectedCheck

      - name: Upload Failing Test Report Log
        if: steps.testing.outcome != 'success'        # upload the generated log on failure of the tests job
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ~/appemulator.log # path to where the log is

      - name: Fail for UI Test
        if: steps.testing.outcome != 'success'
        run: exit 1

      - name: Run Enro UI Tests (Hilt)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: ./gradlew :enro:hilt-test:connectedCheck

      - name: Run Enro Unit Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: ./gradlew :enro:testDebugUnitTest

      - name: Run Modularised Example Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew :modularised-example:app:testDebugUnitTest
