name: CI
on:
  push:
    branches: [main, activity-container-test]
  pull_request:
    branches:
      - main
jobs:
  run-ui-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        env:
          EW_API_TOKEN: ${{ secrets.EW_API_KEY }}
        run: ./gradlew :enro:testDebugWithEmulatorWtf :enro:testDebugUnitTest