name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-ui-tests:
    name: Run Tests
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2.5.0
      with:
        distribution: 'zulu'
        java-version: 11
          
    - name: Run Enro UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew -Pandroid.testInstrumentationRunnerArguments.class=dev.enro.core.fragment.FragmentDestinationPushToSiblingContainer :enro:connectedCheck

    - name: Run Enro UI Tests (Hilt)
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew :enro:hilt-test:connectedCheck

    - name: Run Enro Unit Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew :enro:testDebugUnitTest

    - name: Run Modularised Example Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew :modularised-example:app:testDebugUnitTest
