name: Release
on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew :enro-core:connectedCheck

      - name: Update Version Name
        with:
          api-level: 29
          script: ./gradlew updateVersion -PversionName=${{ github.event.release.tag_name }}

      - name: Publish Release
        env:
          PUBLISH_GITHUB_USER: ${{ secrets.PUBLISH_GITHUB_USER }}
          PUBLISH_GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
          PUBLISH_BINTRAY_USER: ${{ secrets.PUBLISH_BINTRAY_USER }}
          PUBLISH_BINTRAY_TOKEN: ${{ secrets.PUBLISH_BINTRAY_TOKEN }}
        with:
          script: ./gradlew :enro-core:connectedCheck

      - name: Update Repo
        uses: EndBug/add-and-commit@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: "./version.properties"
          author_name: Release Automation
          message: "Release ${{ github.event.release.tag_name }}"
          tag: "${{ github.event.release.tag_name }} --force"
