name: run-ui-tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-ui-tests:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew :enro:connectedCheck