name: run-ui-tests
on: pull-request
jobs:
  run-ui-tests:
    name: Run UI Tests
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        script: ./gradlew :enro:connectedCheck